name: smartcommerce_flutter
description: AI-powered e-commerce recommendation app
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  provider: ^6.0.5
  shared_preferences: ^2.0.17
  cached_network_image: ^3.2.3
  flutter_staggered_grid_view: ^0.6.2
  lottie: ^2.2.0
  speech_to_text: ^6.1.1
  flutter_tts: ^3.6.3
  camera: ^0.10.3
  permission_handler: ^10.2.0
  connectivity_plus: ^3.0.3
  sqflite: ^2.2.6
  path: ^1.8.2
  dio: ^4.0.6
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  json_annotation: ^4.8.0
  flutter_secure_storage: ^7.0.1
  local_auth: ^2.1.6
  firebase_core: ^2.7.0
  firebase_messaging: ^14.2.5
  firebase_analytics: ^10.1.0
  flutter_local_notifications: ^13.0.0
  image_picker: ^0.8.6
  flutter_spinkit: ^5.1.0
  shimmer: ^3.0.0
  card_swiper: ^2.0.4
  flutter_animate: ^4.1.0
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/images/